### ISSUE TITLE
magic number

### ISSUE THREAD

**Issue by pwr-mszczepanik** [krecik1219/BMI_android_app#1]
https://github.com/krecik1219/BMI_android_app/blob/49d197ff0dc5b7211d7f992fb833340dc4cb183b/app/src/main/java/pl/pisquared/a237973_lab1_bmi/BMI.java#L28

co znacza te liczby

**Comment by szelinskip** [comment]
to granice bmi, dla ktorych jest niedowaga, waga prawidlowa, nadwaga itp. Ma Pan rację, że to powinno być wyciągnięte do stałych, zapomniałem o tych liczbach.
